# 1. Виконати набір вправ. Всі завдання виконати 2 способами:
- а) з використанням універсальних функцій бібліотеки NumPy.
- b) за допомогою ітеративних конструкцій (з використанням
циклів, спискових включень тощо).
- с) для обох випадків підрахувати час виконання скрипту та
зробити висновки.

## Варіант 5

In [3]:
import numpy as np
import random

## Вправа 3. 
Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [72]:
# Введення чисел n, m, r, c
n = int(input("Введіть n: "))
m = int(input("Введіть m: "))
r = int(input("Введіть r: "))
c = int(input("Введіть c: "))

Введіть n: 6
Введіть m: 7
Введіть r: 2
Введіть c: 3


In [73]:
%%time
# Використання NumPy для створення масиву
array_np = np.ones((n, m), dtype=int)

# Заміна елементів у рядку r на 0
array_np[::r, :] = 0

# Заміна елементів у стовпці c на 0
array_np[:, ::c] = 0

print("Масив за допомогою NumPy:")
print(array_np)

Масив за допомогою NumPy:
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [74]:
%%time
# Використання ітеративних конструкцій для створення масиву
array_iter = [[0 if i % r == 0 or j % c == 0 else 1 for j in range(m)] for i in range(n)] 

print("Масив за допомогою ітеративних конструкцій:")
for row in array_iter:
    print(row)

Масив за допомогою ітеративних конструкцій:
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
CPU times: total: 0 ns
Wall time: 0 ns


## Вправа 5. 
Вводиться число n. Вивести масив розміру n×n, в
якому в рядках з парними індексами стоять 1, а в інших – 0.

In [5]:
# Введення числа n
n = int(input("Введіть n: "))

Введіть n: 5


In [75]:
%%time
# Використання NumPy для створення масиву
array_np = np.zeros((n, n), dtype=int)

# Заміна елементів у рядках з парними індексами на 1
array_np[::2, :] = 1

print("Масив за допомогою NumPy:")
print(array_np)

Масив за допомогою NumPy:
[[1 1 1 1 1 1]
 [0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [0 0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [76]:
%%time
# Використання ітеративних конструкцій для створення масиву
array_iter = [[1 if i % 2 == 0 else 0 for j in range(n)] for i in range(n)]

print("Масив за допомогою ітеративних конструкцій:")
for row in array_iter:
    print(row)

Масив за допомогою ітеративних конструкцій:
[1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 1.01 ms


## Вправа 7. 
З клавіатури вводиться масив. Замінити всі нульові
елементи на –1.

In [8]:

# Введення масиву з клавіатури
input_array = input("Введіть елементи масиву через пробіл: ").split()
input_array = [int(element) for element in input_array]
# input_array = np.random.randint(0, 2, 100000)
# input_array

Введіть елементи масиву через пробіл: 3 4 0 6 5 0 3 0 4


In [9]:
%%time

import numpy as np

# Введення масиву з клавіатури
np_array = np.array(input_array)

# Заміна нульових елементів на -1
np_output = np.where(np_array == 0, -1, input_array)

# Виведення результату
print("Масив після заміни нульових елементів на -1:", np_output)

Масив після заміни нульових елементів на -1: [ 3  4 -1  6  5 -1  3 -1  4]
CPU times: total: 0 ns
Wall time: 0 ns


In [10]:
%%time

# Заміна нульових елементів на -1 за допомогою спискового включення
output_array = [-1 if element == 0 else element for element in input_array]

# Виведення результату
print("Масив після заміни нульових елементів на -1:", output_array)

Масив після заміни нульових елементів на -1: [3, 4, -1, 6, 5, -1, 3, -1, 4]
CPU times: total: 0 ns
Wall time: 0 ns


## Вправа 10. 
Вводиться числа n i m. Створити масив випадкових
значень n×m і обчислити мінімальне, максимальне значення, середнє та
середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [14]:
# Введення чисел n і m
n = int(input("Введіть n: "))
m = int(input("Введіть m: "))

Введіть n: 4
Введіть m: 5


In [16]:
%%time
array_np = np.random.rand(n, m)
print("Згенерований масив: ", array_np)
# Обчислення мінімального, максимального значень, середнього та середньо квадратичного відхилення
min_value = np.min(array_np)
max_value = np.max(array_np)
mean_value = np.mean(array_np)
std_deviation = np.std(array_np)

# Виведення результатів
print("Мінімальне значення:", round(min_value, 3))
print("Максимальне значення:", round(max_value, 3))
print("Середнє значення:", round(mean_value, 3))
print("Середньо квадратичне відхилення:", round(std_deviation, 3))

Згенерований масив:  [[0.00832097 0.27559047 0.37286253 0.11009716 0.70507249]
 [0.68017105 0.17699645 0.28405661 0.43473713 0.32324645]
 [0.40323145 0.96384245 0.98745653 0.88245933 0.7405769 ]
 [0.84090457 0.87606631 0.91139742 0.19479828 0.22096553]]
Мінімальне значення: 0.008
Максимальне значення: 0.987
Середнє значення: 0.52
Середньо квадратичне відхилення: 0.314


In [77]:
%%time
# Створення масиву випадкових значень n×m за допомогою ітеративних конструкцій
array_iter = [[random.random() for j in range(m)] for i in range(n)]

# Обчислення мінімального, максимального значень, середнього та середньо квадратичного відхилення
min_value = min(min(row) for row in array_iter)
max_value = max(max(row) for row in array_iter)
mean_value = sum(sum(row) for row in array_iter) / (n * m)
std_deviation = (sum((x - mean_value) ** 2 for row in array_iter for x in row) / (n * m)) ** 0.5

# Виведення результатів
print("Згенерований масив: ", array_iter)
print("Мінімальне значення:", round(min_value, 3))
print("Максимальне значення:", round(max_value, 3))
print("Середнє значення:", round(mean_value, 3))
print("Середньо квадратичне відхилення:", round(std_deviation, 3))

Згенерований масив:  [[0.23881245663866335, 0.6835758951651152, 0.5895664206732022, 0.5897928018401389, 0.37747798329628746, 0.17799754979551163, 0.3176727325038028], [0.5255810241526071, 0.30970215851834715, 0.6449905537940661, 0.0841203029550397, 0.16970575063532756, 0.7721055157737522, 0.7672786454359081], [0.2189626935190443, 0.2185547514953653, 0.35368314832841297, 0.4792151447886742, 0.6576979671146679, 0.42624852353486054, 0.025862319857820948], [0.1963425727046606, 0.3179402881719823, 0.5529348016961805, 0.3353495339111121, 0.6323694240648271, 0.7592587455279411, 0.8591217254861397], [0.10854134965925877, 0.49672763627341765, 0.42700495091655055, 0.8582543067921089, 0.7772519946775026, 0.19602120556150215, 0.35670047120674087], [0.4449072858428679, 0.7725140865100676, 0.655743619215846, 0.36643245285568204, 0.07957127806589426, 0.6373231107051187, 0.9536768726878541]]
Мінімальне значення: 0.026
Максимальне значення: 0.954
Середнє значення: 0.462
Середньо квадратичне відхилення:

## Вправа 12. 
Створити масив одиниць розміром n×n та створити в
ньому «рамку», що утворюється з 0.

In [24]:
n = int(input("Введіть n: "))

Введіть n: 4


In [79]:
%%time
# Створення масиву одиниць розміром n×n за допомогою NumPy
array_np = np.zeros((n, n), dtype=int)

# Створення "рамки" з нулів
array_np[1:-1, 1:-1] = 1

print("Масив за допомогою NumPy:")
print(array_np)

Масив за допомогою NumPy:
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 0 ns


In [80]:
%%time
# Створення масиву одиниць розміром n×n за допомогою ітеративних конструкцій
array_iter = [[0 if i == 0 or i == n - 1 or j == 0 or j == n - 1 else 1 for j in range(n)] for i in range(n)]

print("Масив за допомогою ітеративних конструкцій:")
for row in array_iter:
    print(row)

Масив за допомогою ітеративних конструкцій:
[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 0 ns


## Вправа 14. 
Розмістити на полі 8×8 нулі та одиниці в шахматному
порядку, використовуючи функцію numpy tile().

In [81]:
%%time
# Створення масиву 8x8 з нулів та одиниць в шахматному порядку за допомогою NumPy
array_np = np.tile([[0, 1], [1, 0]], (4, 4))

print("Масив за допомогою NumPy:")
print(array_np)

Масив за допомогою NumPy:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
CPU times: total: 0 ns
Wall time: 1.02 ms


In [83]:
%%time
# Створення масиву 8x8 з нулів та одиниць в шахматному порядку за допомогою ітеративних конструкцій
array_iter = [[(i + j) % 2 for j in range(8)] for i in range(8)]

print("Масив за допомогою ітеративних конструкцій:")
for row in array_iter:
    print(row)

Масив за допомогою ітеративних конструкцій:
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
CPU times: total: 15.6 ms
Wall time: 982 µs


In [ ]:
# 2. Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
- a) матричного множення;
- b) оберненої матриці;
- c) функції numpy.linalg.solve().

Порівняти всі рішення за допомогою функції numpy.allclose().

$$\begin{equation}
  \left\{
  \begin{aligned}
     & x_1 + 3x_2 + 5x_3 + 7x_4 &= 12 \\
     & 3x_1 + 5x_2 + 7x_3 + x_4 &= 0 \\
     & 5x_1 + 7x_2 + x_3 + 3x_4 &= 4 \\
     & 7x_1 + x_2 + 3x_3 + 5x_4 &= 16
  \end{aligned}
  \right.
\end{equation}$$

In [39]:
# Основна матриця системи
A = np.array([[1, 3, 5, 7],
              [3, 5, 7, 1],
              [5, 7, 1, 3],
              [7, 1, 3, 5]])

# Вектор вільних членів
B = np.array([12, 0, 4, 16])

# Визначник основної матриці
det_A = np.linalg.det(A)

# Знаходження визначників матриць, отриманих заміною відповідних стовпців вектором вільних членів
det_A1 = np.linalg.det(np.column_stack((B, A[:, 1:])))
det_A2 = np.linalg.det(np.column_stack((A[:, 0], B, A[:, 2:])))
det_A3 = np.linalg.det(np.column_stack((A[:, :2], B, A[:, 3])))
det_A4 = np.linalg.det(np.column_stack((A[:, :3], B)))

# Знаходження значень невідомих за формулами Крамера
x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A
x4 = det_A4 / det_A
X = np.array([x1, x2, x3, x4])
# Виведення результатів
print("Значення невідомих за допомогою формул Крамера:")
print("x1 =", x1)
print("x2 =", x2)
print("x3 =", x3)
print("x4 =", x4)

# Перевірка за допомогою матричного множення
result_check = np.dot(A, np.array([x1, x2, x3, x4]))
all_close_matrix_mult = np.allclose(result_check, B)
print("\nПеревірка за допомогою матричного множення:")
print("A * X =", result_check)
print("Вектор вільних членів B =", B)
print("Всі значення однакові:", all_close_matrix_mult)

# Перевірка за допомогою оберненої матриці
A_inv = np.linalg.inv(A)
result_check_inv = np.dot(A_inv, B)
all_close_inv = np.allclose(result_check_inv, X)
print("\nПеревірка за допомогою оберненої матриці:")
print("A_inv * B =", result_check_inv)
print("Всі значення однакові:", all_close_inv)

# Перевірка за допомогою функції numpy.linalg.solve()
result_solve = np.linalg.solve(A, B)
all_close_solve = np.allclose(result_solve, X)
print("\nПеревірка за допомогою numpy.linalg.solve():")
print("numpy.linalg.solve(A, B) =", result_solve)
print("Всі значення однакові:", all_close_solve)

Значення невідомих за допомогою формул Крамера:
x1 = 1.0000000000000009
x2 = -1.0000000000000009
x3 = -7.853566282149544e-17
x4 = 2.0

Перевірка за допомогою матричного множення:
A * X = [ 1.20000000e+01 -2.22044605e-15  4.00000000e+00  1.60000000e+01]
Вектор вільних членів B = [12  0  4 16]
Всі значення однакові: True

Перевірка за допомогою оберненої матриці:
A_inv * B = [ 1.00000000e+00 -1.00000000e+00 -1.66533454e-16  2.00000000e+00]
Всі значення однакові: True

Перевірка за допомогою numpy.linalg.solve():
numpy.linalg.solve(A, B) = [ 1.00000000e+00 -1.00000000e+00 -5.24271984e-17  2.00000000e+00]
Всі значення однакові: True


## Вправа 21
Ввести числа n і m. Згенерувати матрицю n×n
випадкових цілих елементів з діапазону [0, m]. Замінити всі
максимальні елементи цієї матриці на протилежні за знаком.

In [4]:
n = int(input())
m = int(input())
matrix = np.random.randint(0, m+1, size=(n, n))
print("Матриця:")
print(matrix)

4
10
Матриця:
[[ 4  4  5  3]
 [ 7  1  3  0]
 [10  0 10  0]
 [ 3  8  7  4]]


In [5]:
%%time

matrix_a = matrix.copy()
max_value = np.max(matrix_a)
matrix_a[matrix_a == max_value] *= -1

print("Матриця з використанням NumPy:")
print(matrix_a)

Матриця з використанням NumPy:
[[  4   4   5   3]
 [  7   1   3   0]
 [-10   0 -10   0]
 [  3   8   7   4]]
CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
%%time

matrix_a = matrix.copy()
max_value = max(max(row) for row in matrix_a)

for i in range(n):
    for j in range(n):
        if matrix_a[i][j] == max_value:
            matrix_a[i][j] *= -1

print("Матриця з використанням ітерацій:")
for row in matrix_a:
    print(row)

Матриця з використанням ітерацій:
[4 4 5 3]
[7 1 3 0]
[-10   0 -10   0]
[3 8 7 4]
CPU times: total: 0 ns
Wall time: 1.01 ms


# 3. Обчислити значення матричного виразу 
$$ (A-B^2)(2A+B)$$, де $$
A = 
    \begin{pmatrix}
      5 & 2 & 0 \\
      10 & 4 & 1 \\
      7 & 3 & 2 \\
    \end{pmatrix}
B = 
    \begin{pmatrix}
      3 & 6 & -1 \\
      -1 & -2 & 0 \\
      2 & 1 & 3 \\
    \end{pmatrix}
$$
 - а) з використанням універсальних функцій бібліотеки NumPy.
 - b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
 - с) для обох випадків підрахувати час виконання скрипту та зробити висновок.
Порівняти всі рішення за допомогою функції numpy.allclose().



In [63]:

# Задання матриць A і B
A = np.array([[5, 2, 0],
              [10, 4, 1],
              [7, 3, 2]])

B = np.array([[3, 6, -1],
              [-1, -2, 0],
              [2, 1, 3]])



In [67]:
%%time
# Обчислення значення матричного виразу за допомогою універсальних функцій NumPy
result_np = np.dot((A - np.dot(B, B)), (2 * A + B))


# Виведення результатів
print("Результат за допомогою універсальних функцій NumPy:")
print(result_np)

# Порівняння рішень за допомогою numpy.allclose()
# are_close = np.allclose(result_np, result_iter)
# print("\nЧи значення близькі за допомогою numpy.allclose():", are_close)

Результат за допомогою універсальних функцій NumPy:
[[  91   64   32]
 [ 257  146    1]
 [-322 -135  -51]]
CPU times: total: 0 ns
Wall time: 0 ns


In [68]:
%%time 
# Обчислення значення матричного виразу за допомогою ітеративних конструкцій
def multiply_matrices(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix2[0])):
            element = 0
            for k in range(len(matrix2)):
                element += matrix1[i][k] * matrix2[k][j]
            row.append(element)
        result.append(row)
    return result

def multiply_matrix_by_scalar(matrix, scalar):
    result = []
    for row in matrix:
        new_row = [element * scalar for element in row]
        result.append(new_row)
    return result

def substract_matrix(matrix1, matrix2):
    result = [[matrix1[i][j] - matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
    return result

def sum_matrix(matrix1, matrix2):
    result = [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]
    return result

# Знаходимо значення матриці B^2
B_squared = multiply_matrices(B, B)
# Віднімаємо від матриці A матрицю B^2
first = substract_matrix(A, B_squared)
a2 = multiply_matrix_by_scalar(A, 2)
second = sum_matrix(a2, B)
# Домножуємо результат на матрицю (2A+B)
final_result = multiply_matrices(first, second)

# Виводимо результат
print(final_result)

[[91, 64, 32], [257, 146, 1], [-322, -135, -51]]
CPU times: total: 0 ns
Wall time: 0 ns


In [69]:
np.allclose(result_np, final_result)

True